#                                                                        #
# Settings Configuration for the Fluid Package                           #
#                                                                        #

# $Id:$

Fluid:
  syntaxTreeCache:
    enable: y
