Neos:
  Flow:
    http:
      middlewares:
        'ajaxWidget':
          position: 'before routing'
          middleware: 'Neos\FluidAdaptor\Core\Widget\AjaxWidgetMiddleware'
    mvc:
      view:
        defaultImplementation: 'Neos\FluidAdaptor\View\TemplateView'

    error:
      exceptionHandler:
        # default options for all rendering groups (see below). Options can be overridden in the respective rendering group
        defaultRenderingOptions:
          viewClassName: Neos\FluidAdaptor\View\StandaloneView
