TYPO3:
  Flow:
    http:
      chain:
        'process':
          chain:
            'ajaxWidget':
              position: 'before routing'
              component: 'Neos\FluidAdaptor\Core\Widget\AjaxWidgetComponent'
